insert into public.categories (slug, name, description, sort_order)
values
  ('planery', 'Planery', 'Szablony do planowania dnia, tygodnia, pracy i nawyków w eleganckiej formie.', 1),
  ('przepisy', 'Przepisy', 'Praktyczne e-booki kulinarne z dopracowaną estetyką i prostym wdrożeniem.', 2),
  ('plany-treningowe', 'Plany treningowe', 'Plany progresji i regularności dla domu lub siłowni.', 3),
  ('finanse', 'Finanse', 'Nowoczesne produkty cyfrowe do budżetu i spokojniejszych decyzji finansowych.', 4),
  ('rozwoj-osobisty', 'Rozwój osobisty', 'Workbooki i dzienniki wspierające refleksję, pewność siebie i rozwój.', 5)
on conflict (slug) do update
set name = excluded.name,
    description = excluded.description,
    sort_order = excluded.sort_order;

with category_map as (
  select id, slug
  from public.categories
)
insert into public.products (
  slug,
  category_id,
  name,
  short_description,
  description,
  price,
  compare_at_price,
  format,
  pages,
  tags,
  rating,
  sales_label,
  accent,
  cover_gradient,
  includes,
  hero_note,
  bestseller,
  featured
)
values
  (
    'planner-zlota-rutyna',
    (select id from category_map where slug = 'planery'),
    'Planner Złota Rutyna',
    'Codzienny system planowania premium dla osób, które chcą działać spokojniej i skuteczniej.',
    'Elegancki planner PDF z tygodniowymi i miesięcznymi układami, trackerami nawyków oraz sekcjami refleksji. Zaprojektowany tak, by łączyć wysoką estetykę z realnym porządkiem dnia.',
    79,
    109,
    'PDF + GoodNotes',
    86,
    array['organizacja', 'nawyki', 'goodnotes'],
    4.9,
    'Najczęściej wybierany przez klientki premium',
    'from-amber-300/70 via-yellow-500/40 to-orange-300/20',
    'from-stone-950 via-amber-950/70 to-stone-900',
    array['plan miesięczny i tygodniowy', 'trackery nawyków i energii', 'sekcję priorytetów i refleksji'],
    'Dla osób, które chcą planować bez chaosu.',
    true,
    true
  ),
  (
    'planner-biznesowy-noir',
    (select id from category_map where slug = 'planery'),
    'Planner Biznesowy Noir',
    'System celów, zadań i analiz dla marek osobistych, konsultantek i właścicielek biznesów.',
    'Rozbudowany planner z podziałem na kampanie, cele kwartalne, KPI oraz szablony planowania contentu. Idealny do prowadzenia nowoczesnego biznesu cyfrowego.',
    99,
    139,
    'PDF',
    104,
    array['biznes', 'cele', 'content'],
    4.8,
    'Ulubiony wybór twórczyń cyfrowych',
    'from-yellow-200/70 via-amber-400/40 to-yellow-600/20',
    'from-neutral-950 via-zinc-900 to-neutral-800',
    array['dashboard kwartalny', 'plan kampanii i lejka sprzedaży', 'arkusze celów i KPI'],
    'Planowanie pod markę, sprzedaż i regularność.',
    false,
    true
  ),
  (
    'ebook-fit-kuchnia-15-minut',
    (select id from category_map where slug = 'przepisy'),
    'E-book Fit Kuchnia 15 Minut',
    'Szybkie przepisy na codzienny rytm bez liczenia każdego składnika.',
    'Kolekcja prostych, efektownych przepisów z listami zakupów i zamiennikami. Skierowana do osób, które chcą jeść dobrze, ale nie mają czasu na skomplikowane gotowanie.',
    59,
    89,
    'PDF',
    58,
    array['fit', 'meal prep', 'szybkie przepisy'],
    4.7,
    'Świetny start dla zabieganych',
    'from-yellow-100/80 via-amber-300/40 to-lime-200/20',
    'from-stone-950 via-yellow-950/60 to-emerald-950/50',
    array['45 szybkich przepisów', 'listy zakupów', 'zamienniki i wskazówki meal prep'],
    'Jedzenie, które wspiera tempo życia, nie spowalnia go.',
    true,
    false
  ),
  (
    'ebook-luksusowe-desery-zero-chaosu',
    (select id from category_map where slug = 'przepisy'),
    'Luksusowe Desery Zero Chaosu',
    'Estetyczne desery premium w domowej, uproszczonej wersji.',
    'Przepisy inspirowane cukierniczym stylem premium, ale stworzone z myślą o codziennej kuchni. Każdy deser zawiera wariant podstawowy i efektowną wersję na specjalne okazje.',
    69,
    99,
    'PDF',
    46,
    array['desery', 'premium', 'estetyka'],
    4.8,
    'Najbardziej instagramowy produkt w katalogu',
    'from-amber-100/80 via-orange-300/40 to-rose-200/20',
    'from-zinc-950 via-stone-900 to-orange-950/40',
    array['24 desery krok po kroku', 'warianty podstawowe i premium', 'wskazówki do stylizacji pod zdjęcia'],
    'Dla klientów, którzy kochają smak i prezentację.',
    false,
    false
  ),
  (
    'plan-treningowy-sylwetka-premium',
    (select id from category_map where slug = 'plany-treningowe'),
    'Plan Treningowy Sylwetka Premium',
    '12-tygodniowy plan treningowy do domu lub na siłownię, z naciskiem na proporcje i konsekwencję.',
    'Kompletny plan progresji, checklisty techniczne i harmonogram regeneracji. Zaprojektowany dla osób, które chcą rezultatów bez przypadkowych treningów.',
    89,
    129,
    'PDF + tracker',
    72,
    array['trening', 'sylwetka', '12 tygodni'],
    4.9,
    'Top wybór w kategorii trening',
    'from-yellow-100/80 via-amber-400/40 to-red-300/20',
    'from-black via-stone-900 to-red-950/50',
    array['plan 3 i 4 dniowy', 'trackery postępów', 'sekcję regeneracji i mobilności'],
    'Konkretny plan, który porządkuje cały proces.',
    true,
    true
  ),
  (
    'plan-home-body-balance',
    (select id from category_map where slug = 'plany-treningowe'),
    'Home Body Balance',
    'Kobiecy plan domowy z gumami i hantlami, nastawiony na rytm i regularność.',
    'Plan dla osób, które trenują w domu i chcą czuć prowadzenie krok po kroku. Zawiera modyfikacje poziomu, plan tygodnia i mini-sekcję mobility.',
    69,
    99,
    'PDF',
    54,
    array['dom', 'regularność', 'mobilność'],
    4.7,
    'Idealny wybór na start',
    'from-yellow-100/70 via-amber-300/40 to-pink-300/20',
    'from-neutral-950 via-stone-900 to-pink-950/40',
    array['plan 4-tygodniowy', 'wersje light i standard', 'trackery energii i motywacji'],
    'Lekkość formy, konsekwencja w efektach.',
    false,
    false
  ),
  (
    'budzet-domowy-z-klasa',
    (select id from category_map where slug = 'finanse'),
    'Budżet Domowy z Klasą',
    'Arkusz i przewodnik do zarządzania budżetem w nowoczesnym, luksusowym stylu.',
    'Zestaw templatek do kontroli wydatków, budowy poduszki finansowej i planowania większych celów. Przygotowany dla osób, które chcą uporządkować finanse bez uczucia ograniczenia.',
    79,
    119,
    'PDF + arkusz',
    63,
    array['budżet', 'arkusz', 'planowanie'],
    4.8,
    'Bestseller w finansach osobistych',
    'from-yellow-100/80 via-amber-400/45 to-emerald-300/20',
    'from-stone-950 via-emerald-950/40 to-zinc-900',
    array['dashboard wydatków', 'szablon celów finansowych', 'plan poduszki i oszczędności'],
    'Porządek w finansach bez surowego excela.',
    true,
    true
  ),
  (
    'mini-kurs-cena-spokoj-finansowy',
    (select id from category_map where slug = 'finanse'),
    'Mini Kurs Cena Spokój Finansowy',
    'Lekki kurs PDF o nawykach, priorytetach i budowaniu zdrowych decyzji finansowych.',
    'Produkt dla osób, które chcą nie tylko zapisywać liczby, ale rozumieć swoje decyzje zakupowe i budować większe poczucie bezpieczeństwa.',
    49,
    79,
    'PDF',
    39,
    array['mindset', 'finanse', 'nawyki'],
    4.6,
    'Najbardziej przystępny produkt startowy',
    'from-amber-100/80 via-yellow-300/40 to-cyan-200/20',
    'from-neutral-950 via-slate-950 to-cyan-950/40',
    array['ćwiczenia refleksyjne', 'mapę priorytetów', 'mikro-plan 30 dni'],
    'Finanse jako spokój, nie presja.',
    false,
    false
  ),
  (
    'dziennik-pewnosci-siebie',
    (select id from category_map where slug = 'rozwoj-osobisty'),
    'Dziennik Pewności Siebie',
    'Elegancki workbook do budowania pewności, granic i sprawczości.',
    'Pytania coachingowe, ćwiczenia na przekonania i tygodniowy rytuał domykania myśli. Stworzony dla osób, które chcą rozwijać pewność siebie w praktyce, nie tylko w teorii.',
    69,
    99,
    'PDF',
    64,
    array['mindset', 'workbook', 'pewność siebie'],
    4.9,
    'Najwyżej oceniany workbook',
    'from-yellow-100/70 via-amber-400/45 to-violet-300/15',
    'from-black via-zinc-900 to-violet-950/40',
    array['30 promptów rozwojowych', 'ćwiczenia granic i odwagi', 'tygodniowy rytuał podsumowania'],
    'Rozwój osobisty bez banału i przesady.',
    false,
    true
  )
on conflict (slug) do update
set
  category_id = excluded.category_id,
  name = excluded.name,
  short_description = excluded.short_description,
  description = excluded.description,
  price = excluded.price,
  compare_at_price = excluded.compare_at_price,
  format = excluded.format,
  pages = excluded.pages,
  tags = excluded.tags,
  rating = excluded.rating,
  sales_label = excluded.sales_label,
  accent = excluded.accent,
  cover_gradient = excluded.cover_gradient,
  includes = excluded.includes,
  hero_note = excluded.hero_note,
  bestseller = excluded.bestseller,
  featured = excluded.featured;
